# Generated by Django 3.2.2 on 2022-08-27 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0001_initial'),
        ('finance', '0002_invoice_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corecode.academicyear'),
        ),
    ]
